[workspace]
members = [
    "lib",
    "examples/verify_account",
    "examples/verify_storage",
    "examples/verify_header",
    "examples/verify_transaction",
    "examples/verify_receipt",
]
default-member = "lib"
